// src/components/KpiBoard.tsx
import { supabase } from '../supabaseClient';
import useSWR from 'swr';
import { useEffect } from 'react';

type Kpi = {
  position_cost: number;
  intraday_realized: number;
  intraday_unreal: number;
  day_trades: number;
  total_trades: number;
  wtd_pnl: number;
  mtd_pnl: number;
  ytd_pnl: number;
};

async function fetchKpi() {
  const { data, error } = await supabase.from('vw_kpi_stats').select('*').single();
  if (error) throw error;
  return data as Kpi;
}

const labelMap: Record<keyof Kpi, string> = {
  position_cost: '账户持仓金额',
  intraday_realized: '日内交易统计',
  intraday_unreal: '当日盈亏统计',
  day_trades: '当日交易次数',
  total_trades: '累计交易笔数',
  wtd_pnl: 'WTD 盈亏',
  mtd_pnl: 'MTD 盈亏',
  ytd_pnl: 'YTD 盈亏'
};

export default function KpiBoard(){
  const { data } = useSWR('kpi', fetchKpi, { refreshInterval: 10000 });

  if (!data) return null;

  return (
    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
      {Object.entries(labelMap).map(([field, label])=>{
        const val = (data as any)[field] as number;
        const cls = val >= 0 ? 'text-emerald-400' : 'text-red-400';
        return (
          <div key={field} className="p-4 rounded-xl bg-neutral-800 shadow">
            <div className="text-sm text-neutral-400">{label}</div>
            <div className={`text-xl font-semibold ${cls}`}>{val.toFixed(2)}</div>
          </div>
        );
      })}
    </div>
  );
}

// src/components/KpiBoard.vue

<template>
  <div class="grid sm:grid-cols-2 md:grid-cols-4 gap-4">
    <div v-for="k in kpis" :key="k.key" class="bg-white p-4 rounded-2xl shadow flex flex-col">
      <span class="text-xs text-gray-500">{{ k.label }}</span>
      <span :class="valueColor(k.value)" class="text-2xl font-semibold">{{ format(k.value) }}</span>
    </div>
  </div>
</template>

<script setup>
import { ref, watchEffect } from 'vue'
import useSWRV from 'swrv'
import { supabase } from '../supabaseClient'

const kpis = ref([
  { key:'position_amount', label:'账户持仓金额', value:0 },
  { key:'intraday_realized', label:'日内交易统计', value:0 },
  { key:'intraday_unrealized_placeholder', label:'当日盈亏统计', value:0 },
  { key:'day_trades', label:'当日交易次数', value:0 },
  { key:'total_trades', label:'累计交易笔数', value:0 },
  { key:'wtd_pnl', label:'WTD 盈亏', value:0 },
  { key:'mtd_pnl', label:'MTD 盈亏', value:0 },
  { key:'ytd_pnl', label:'YTD 盈亏', value:0 }
])

const fetcher = async () => {
  const uid = (await supabase.auth.getUser()).data.user.id
  const { data, error } = await supabase.from('vw_kpi_stats').select('*').eq('user_id', uid).single()
  if(error) throw error
  return data
}
const { data } = useSWRV('kpi', fetcher, { refreshInterval: 10000 })
watchEffect(()=>{
  if(data.value){
    kpis.value.forEach(k=>k.value=data.value[k.key]||0)
  }
})

function format(n){ return (+n||0).toFixed(2) }
function valueColor(n){ return n>0?'text-emerald-500':n<0?'text-red-500':'text-gray-600' }
</script>
