// src/components/KpiBoard.tsx
import { supabase } from '../supabaseClient';
import useSWR from 'swr';
import { useEffect } from 'react';

type Kpi = {
  position_cost: number;
  intraday_realized: number;
  intraday_unreal: number;
  day_trades: number;
  total_trades: number;
  wtd_pnl: number;
  mtd_pnl: number;
  ytd_pnl: number;
};

async function fetchKpi() {
  const { data, error } = await supabase.from('vw_kpi_stats').select('*').single();
  if (error) throw error;
  return data as Kpi;
}

const labelMap: Record<keyof Kpi, string> = {
  position_cost: '账户持仓金额',
  intraday_realized: '日内交易统计',
  intraday_unreal: '当日盈亏统计',
  day_trades: '当日交易次数',
  total_trades: '累计交易笔数',
  wtd_pnl: 'WTD 盈亏',
  mtd_pnl: 'MTD 盈亏',
  ytd_pnl: 'YTD 盈亏'
};

export default function KpiBoard(){
  const { data } = useSWR('kpi', fetchKpi, { refreshInterval: 10000 });

  if (!data) return null;

  return (
    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
      {Object.entries(labelMap).map(([field, label])=>{
        const val = (data as any)[field] as number;
        const cls = val >= 0 ? 'text-emerald-400' : 'text-red-400';
        return (
          <div key={field} className="p-4 rounded-xl bg-neutral-800 shadow">
            <div className="text-sm text-neutral-400">{label}</div>
            <div className={`text-xl font-semibold ${cls}`}>{val.toFixed(2)}</div>
          </div>
        );
      })}
    </div>
  );
}

// src/components/KPIBoard.vue
<template>
  <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
    <div v-for="item in items" :key="item.key" class="p-4 rounded-xl bg-neutral-800">
      <div class="text-sm text-neutral-400">{{ item.label }}</div>
      <div :class="[item.value>=0?'text-emerald-400':'text-red-400','text-xl font-semibold']">
        {{ item.value.toFixed(2) }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { supabase } from '../supabase';
import { Trade } from '../types';
import { computeKPIs, KPI } from '../utils/compute';
import axios from 'axios';

const items = ref<{key:string,label:string,value:number}[]>([]);

async function load(){
  const { data, error } = await supabase.from('TradeDate').select('*');
  if(error) return console.error(error);
  const trades = data as any as Trade[];

  // fetch quotes for all symbols
  const symbols = [...new Set(trades.map(t=>t.symbol))];
  const quotes: Record<string,{c:number,pc:number}> = {};
  const token = import.meta.env.VITE_FINNHUB_TOKEN as string;
  await Promise.all(symbols.map(async s=>{
    const {data} = await axios.get(`https://finnhub.io/api/v1/quote?symbol=${s}&token=${token}`);
    quotes[s]=data;
  }));

  const kpi: KPI = computeKPIs(trades, quotes);

  items.value = [
    {key:'positionCost',label:'账户持仓金额',value:kpi.positionCost},
    {key:'intradayRealized',label:'日内交易统计',value:kpi.intradayRealized},
    {key:'intradayUnreal',label:'当日盈亏统计',value:kpi.intradayUnreal},
    {key:'dayTrades',label:'当日交易次数',value:kpi.dayTrades},
    {key:'totalTrades',label:'累计交易笔数',value:kpi.totalTrades},
    {key:'wtdPnl',label:'WTD 盈亏',value:kpi.wtdPnl},
    {key:'mtdPnl',label:'MTD 盈亏',value:kpi.mtdPnl},
    {key:'ytdPnl',label:'YTD 盈亏',value:kpi.ytdPnl},
  ];
}

onMounted(load);
</script>
